Paintball:
  name: Paintball
  command: pb
  prefix: '&f[Paintball]&e'
  signDisplayName: '&f[Paintball]&e'
  gameSize:
    nTeams: 2-14
    teamSize: '1'
  nLives: '1'
  victoryCondition: HIGHESTKILLS
  tracking:
    database: Paintball
    rated: true
    useTrackerMessages: false
  arenaType: Paintball
  arenaClass: PaintballArena
  defaults:
    options:
    - woolTeams
  onEnter:
    options:
    - STOREALL
  onLeave:
    options:
    - RESTOREALL
  onStart:
    options:
    - teleportIn
    - pvpOn
  onComplete:
    options:
    - teleportOut
    - clearInventory
  onSpawn:
    giveItems:
    - SNOW_BALL 128
    options:
    - health=20.0
    - hunger=20
  onDeath:
    options:
    - clearInventory
  winners:
    options:
    - health=20.0
    - hunger=20
