name: ${project.name}
version: ${project.version}

main: mc.alk.paintball.Paintball
depend: [BattleArena]
authors: [Alkarin]

commands:
    paintball:
        aliases: [pb]
        description: /paintball
        usage: /paintball
    epaintball:
        aliases: [epb]
        description: /epaintball
        usage: /epaintball
