name: ArenaPaintball
main: mc.alk.paintball.Paintball
version: 1.1.3
depend: [BattleArena]
authors: [alkarin_v]

commands:
    paintball:
        aliases: [pb]
        description: /paintball
        usage: /paintball
    epaintball:
        aliases: [epb]
        description: /epaintball
        usage: /epaintball